// import { Geist, Geist_Mono } from "next/font/google";
import { Unbounded, Montserrat } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["cyrillic-ext"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic-ext"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Тема для всего приложения
const theme = {
  colors: {
    background: {
      from: "#13111d",
      via: "#151a24",
      to: "#131d1d"
    }
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} ${montserrat.variable} antialiased min-h-screen`}
        style={{
          background: `linear-gradient(135deg, ${theme.colors.background.from}, ${theme.colors.background.via}, ${theme.colors.background.to})`
        }}
      >
        {/* Фоновые градиенты */}
        <div className="fixed inset-0 overflow-hidden">
          <div className="absolute inset-0 opacity-30">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_0%_0%,_rgba(74,59,130,0.15)_0%,_transparent_50%)]" />
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_100%_100%,_rgba(45,110,91,0.15)_0%,_transparent_50%)]" />
          </div>
        </div>

        {/* Основной контент */}
        <div className="relative min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
